AWSTemplateFormatVersion: '2010-09-09'
Description: Parent stack to manage nested stacks

Parameters:
  AthenaDatabaseName:
    Type: String
    Default: 'athena_db'
  S3BucketName:
    Type: String
    Default: 'sl-data-store-{ENTER ALIAS}'
    Description: Name of the S3 bucket to create and store data
  AthenaOutputBucketName:
    Type: String
    Default: 'sl-athena-output-{ENTER ALIAS}'
    Description: Name of the S3 bucket to store Athena query results
  LambdaS3Bucket:
    Type: String
  LambdaS3Key:
    Type: String
  AgentResourceRoleArn:
    Type: String
  CustomerEncryptionKeyArn:
    Type: String
  FoundationModel:
    Type: String

Resources:
  S3AndLambdaStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub 'https://${S3BucketName}/s3-and-lambda-template.yaml'
      Parameters:
        LambdaS3Bucket: !Ref LambdaS3Bucket
        LambdaS3Key: !Ref LambdaS3Key

  AthenaStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub 'https://${S3BucketName}/athena-template.yaml'
      Parameters:
        AthenaDatabaseName: !Ref AthenaDatabaseName
        S3BucketName: !Ref S3BucketName
        AthenaOutputBucketName: !Ref AthenaOutputBucketName
    DependsOn: S3AndLambdaStack

  BedrockAgentStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub 'https://${S3BucketName}/bedrock-agent-template.yaml'
      Parameters:
        AgentResourceRoleArn: !Ref AgentResourceRoleArn
        CustomerEncryptionKeyArn: !Ref CustomerEncryptionKeyArn
        FoundationModel: !Ref FoundationModel
        AthenaOutputBucketName: !Ref AthenaOutputBucketName
    DependsOn: AthenaStack

Outputs:
  S3BucketName:
    Description: 'Name of the S3 bucket created'
    Value: !GetAtt S3AndLambdaStack.Outputs.S3BucketName
  LambdaFunctionName:
    Description: 'Name of the Lambda function created'
    Value: !GetAtt S3AndLambdaStack.Outputs.LambdaFunctionName
  AthenaDatabaseName:
    Description: 'Name of the Athena database created'
    Value: !GetAtt AthenaStack.Outputs.AthenaDatabaseName
  AthenaOutputBucketName:
    Description: 'Name of the S3 bucket for Athena query results'
    Value: !GetAtt AthenaStack.Outputs.AthenaOutputBucketName
  BedrockAgentName:
    Description: 'Name of the Bedrock Agent created'
    Value: !GetAtt BedrockAgentStack.Outputs.BedrockAgentName
  BedrockAgentArn:
    Description: 'ARN of the Bedrock Agent created'
    Value: !GetAtt BedrockAgentStack.Outputs.BedrockAgentArn
